# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CWOne' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking', '~> 3.1.0'
pod 'SDWebImage', '~> 4.0.0'
pod 'Masonry', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.12'
pod 'SVProgressHUD', '~> 2.1.2'
pod 'FLAnimatedImage', '~> 1.0.12'

  # Pods for CWOne

  target 'CWOneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CWOneUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
